BEGIN;

DROP TABLE IF EXISTS 
    "player",
    "team",
    "coach",
    "stadium",
    "nationality",
    "post",
    "championship",
    "city",
    "color",
    "stat"


CREATE TABLE "stadium"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "capacity" BIGINT NOT NULL,
    "city_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY("city_id") REFERENCES "city"("id")
);

CREATE TABLE "team"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "banner" TEXT NOT NULL,
    "created_date" DATE NOT NULL,
    "color_id" INTEGER NOT NULL,
    "stadium_id" INTEGER NOT NULL,
    "championship_id" INTEGER NOT NULL,
    "city_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY("city_id") REFERENCES "city"("id"),
    FOREIGN KEY("stadium_id") REFERENCES "stadium"("id"),
    FOREIGN KEY("color_id") REFERENCES "color"("id"),
    FOREIGN KEY("championship_id") REFERENCES "championship"("id")
);

CREATE TABLE "player"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "lastname" TEXT NOT NULL,
    "firstname" TEXT NOT NULL,
    "birth_date" DATE NOT NULL,
    "height" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL,
    "post_id" INTEGER NOT NULL,
    "nationality_id" BIGINT NOT NULL,
    "team_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "uptdated_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY("team_id") REFERENCES "team"("id"),
    FOREIGN KEY("nationality_id") REFERENCES "nationality"("id"),
    FOREIGN KEY("post_id") REFERENCES "post"("id")
);

CREATE TABLE "nationality"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name_country" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE "post"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name_post" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE "championship"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE "city"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE "stat"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "points_scored" BIGINT NOT NULL,
    "tackle" BIGINT NOT NULL,
    "lastpass" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "uptaded_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY("player_id") REFERENCES "player"("id")
);

CREATE TABLE "color"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" CHAR(11) NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE "coach"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "lastname" TEXT NOT NULL,
    "fisrtname" TEXT NOT NULL,
    "birth_date" DATE NOT NULL,
    "nationality_id" BIGINT NOT NULL,
    "team_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "update_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY("team_id") REFERENCES "team"("id"),
    FOREIGN KEY("nationality_id") REFERENCES "nationality"("id")
);


COMMIT;




